### ISSUE TITLE
Error running npm run dev

### ISSUE THREAD

**Issue by grunch** [lnp2pBot/frontend#3]
Hi @bilthon  I am having this error when I run `npm run dev`

```
npm run dev

> lnp2pbot-market@1.0.0 dev
> nuxt


   ╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.15.8                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   server-side          │
   │   ▸ Target:      server               │
   │                                       │
   │   Listening: http://localhost:3000/   │
   │                                       │
   ╰───────────────────────────────────────╯

ℹ Preparing project for development                                                        17:26:21
ℹ Initial build may take a while                                                           17:26:21
ℹ Discovered Components: .nuxt/components/readme.md                                        17:26:21
✔ Builder initialized                                                                      17:26:21
✔ Nuxt files generated                                                                     17:26:21

● Client █████████████████████████ building (10%) 1/2 modules 1 active
 node_modules/webpack-hot-middleware/client.js

● Server █████████████████████████ building (10%) 1/1 modules 0 active
 

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/grunch/dev/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/grunch/dev/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/grunch/dev/frontend/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/grunch/dev/frontend/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/grunch/dev/frontend/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/grunch/dev/frontend/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/grunch/dev/frontend/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/grunch/dev/frontend/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.2.0
 ✘  ~/dev/frontend  node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 20231.
    at /home/grunch/dev/frontend/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: undefined,
  signal: undefined
}

Node.js v17.2.0
```

**Comment by bilthon** [comment]
I could reproduce this on node `v17.2.0` and will be looking for a solution. In the meantime can you try running it on `v14.17.0` or similar?
